#!/bin/sh
# @name Generic Differential Rover
# @type Rover
# @class Rover


. ${R}etc/init.d/rc.rover_differential_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=remote}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=rover_differential}

param set-default SYS_HITL 0

param set-default CBRK_SUPPLY_CHK 894281
param set-default SIM_BAT_MIN_PCT 100 
param set-default SIM_BAT_DRAIN 0
param set-default COM_LOW_BAT_ACT 0
param set-default EKF2_REQ_GPS_H 0.1
param set-default EKF2_GPS_CHECK 0
param set-default EKF2_MAG_TYPE 0
param set-default EKF2_MAG_CHK_STR 0.4 
param set-default EKF2_MAG_CHK_INC 30 
param set-default SENS_IMU_AUTOCAL 0
param set-default EKF2_ABL_ACCLIM 40.0
param set-default EKF2_NOAID_TOUT 10000000
param set-default SDLOG_MODE 2
param set-default EKF2_ABIAS_INIT 0.1

# TODO Tune Parameters after Proof of concept
param set-default NAV_ACC_RAD 0.5 			# Acceptance Radius

# Differential Parameters
param set-default RD_WHEEL_TRACK 0.335			# Distance from the center of right wheel to the center of left wheel
param set-default RD_TRANS_DRV_TRN 0.174533		# To be tuned
param set-default RD_TRANS_TRN_DRV 0.261799 		# To be tuned
param set-default RD_YAW_STK_GAIN 1.0			# To be tuned but not important

# Rate Control Parameters
param set-default RO_YAW_RATE_I 0.01 			
param set-default RO_YAW_RATE_P 2  			
param set-default RO_YAW_RATE_LIM 1000			
param set-default RO_YAW_ACCEL_LIM 6000			
param set-default RO_YAW_DECEL_LIM 6000					
param set-default RO_YAW_EXPO 0	
param set-default RO_SPEED_RED -1
param set-default PP_LOOKAHD_GAIN 2	    	
param set-default PP_LOOKAHD_MIN 0.5

# Attitude Control Parameters
param set-default RO_YAW_P 3.0			    	# To be tuned

# Velocity Control Parameters
param set-default RO_ACCEL_LIM 2   			# To be tuned
param set-default RO_DECEL_LIM 6		    	# To be tuned
param set-default RO_JERK_LIM 10		    	# To be tuned
param set-default RO_MAX_THR_SPEED 1			# To be tuned
param set-default RO_SPEED_LIM 1		    	# To be tuned
param set-default RO_SPEED_I 0.0    	    	# To be tuned
param set-default RO_SPEED_P 0.0		    	# To be tuned
param set-default RO_SPEED_RED -1		    	# To be tuned

# Actuator mapping
param set-default PWM_MAIN_FUNC1 102        		# left wheel
param set-default PWM_MAIN_FUNC2 101        		# right wheel

